### ISSUE TITLE
Runtime error: Index out of range [0] with length 0

### ISSUE THREAD

**Issue by kelzenberg** [twpayne/go-xmlstruct#22]
The example runs fine:
```sh
echo '<parent><child flag="true">text</child></parent>' | goxmlstruct
```

but if I cat a big XML file into the tooling, I get an error:

```sh
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/twpayne/go-xmlstruct.init.func2({{0x0?, 0x102a154b0?}, {0x102b75ab8?, 0x1?}})
	/Users/xxx/go/pkg/mod/github.com/twpayne/go-xmlstruct@v1.2.0/xmlstruct.go:52 +0x12c
github.com/twpayne/go-xmlstruct.NewGenerator.func1({{0x0?, 0x102a15a5c?}, {0x102b75ab8?, 0x102944800?}})
	/Users/xxx/go/pkg/mod/github.com/twpayne/go-xmlstruct@v1.2.0/generator.go:201 +0x84
github.com/twpayne/go-xmlstruct.(*element).writeGoType.func2(0x10?, 0x14000f0b0e0)
	/Users/xxx/go/pkg/mod/github.com/twpayne/go-xmlstruct@v1.2.0/element.go:179 +0x48
golang.org/x/exp/slices.order2CmpFunc[...](...)
	/Users/xxx/go/pkg/mod/golang.org/x/exp@v0.0.0-20240416160154-fe59bbe5cc7f/slices/zsortanyfunc.go:299
golang.org/x/exp/slices.medianCmpFunc[...]({0x140010eca20?, 0x12, 0x1029046b0}, 0x4?, 0x8, 0xc, 0x140011739e8, 0x14001173e68)
	/Users/xxx/go/pkg/mod/golang.org/x/exp@v0.0.0-20240416160154-fe59bbe5cc7f/slices/zsortanyfunc.go:308 +0x64
golang.org/x/exp/slices.choosePivotCmpFunc[...]({0x140010eca20?, 0x0?, 0x200000149a68360?}, 0x14001173ac8?, 0x102a1da2c?, 0x14001173a98?)
	/Users/xxx/go/pkg/mod/golang.org/x/exp@v0.0.0-20240416160154-fe59bbe5cc7f/slices/zsortanyfunc.go:284 +0x160
golang.org/x/exp/slices.pdqsortCmpFunc[...]({0x140010eca20, 0x12, 0x12}, 0x0, 0x0?, 0x0?, 0x14001173e68?)
	/Users/xxx/go/pkg/mod/golang.org/x/exp@v0.0.0-20240416160154-fe59bbe5cc7f/slices/zsortanyfunc.go:89 +0xd8
golang.org/x/exp/slices.SortFunc[...](...)
	/Users/xxx/go/pkg/mod/golang.org/x/exp@v0.0.0-20240416160154-fe59bbe5cc7f/slices/sort.go:31
github.com/twpayne/go-xmlstruct.(*element).writeGoType(0x14000f0b040, {0x102a9aa78, 0x14001093180}, 0x14001175a30, {0x1400124c270, 0x7})
	/Users/xxx/go/pkg/mod/github.com/twpayne/go-xmlstruct@v1.2.0/element.go:178 +0x6f4
github.com/twpayne/go-xmlstruct.(*element).writeGoType(0x14000e89860, {0x102a9aa78, 0x14001093180}, 0x14001175a30, {0x14001232af6, 0x6})
	/Users/xxx/go/pkg/mod/github.com/twpayne/go-xmlstruct@v1.2.0/element.go:213 +0xa40
github.com/twpayne/go-xmlstruct.(*element).writeGoType(0x14000e897c0, {0x102a9aa78, 0x14001093180}, 0x14001175a30, {0x14001232af0, 0x5})
	/Users/xxx/go/pkg/mod/github.com/twpayne/go-xmlstruct@v1.2.0/element.go:213 +0xa40
github.com/twpayne/go-xmlstruct.(*element).writeGoType(0x14000e89720, {0x102a9aa78, 0x14001093180}, 0x14001175a30, {0x14001232a4c, 0x4})
	/Users/xxx/go/pkg/mod/github.com/twpayne/go-xmlstruct@v1.2.0/element.go:213 +0xa40
github.com/twpayne/go-xmlstruct.(*element).writeGoType(0x14000e881e0, {0x102a9aa78, 0x14001093180}, 0x14001175a30, {0x1400122aa92, 0x3})
	/Users/xxx/go/pkg/mod/github.com/twpayne/go-xmlstruct@v1.2.0/element.go:213 +0xa40
github.com/twpayne/go-xmlstruct.(*element).writeGoType(0x14000e88140, {0x102a9aa78, 0x14001093180}, 0x14001175a30, {0x1400122aa90, 0x2})
	/Users/xxx/go/pkg/mod/github.com/twpayne/go-xmlstruct@v1.2.0/element.go:213 +0xa40
github.com/twpayne/go-xmlstruct.(*element).writeGoType(0x14000e880a0, {0x102a9aa78, 0x14001093180}, 0x14001175a30, {0x102a5a630, 0x1})
	/Users/xxx/go/pkg/mod/github.com/twpayne/go-xmlstruct@v1.2.0/element.go:213 +0xa40
github.com/twpayne/go-xmlstruct.(*element).writeGoType(0x1400012a320, {0x102a9aa78, 0x14001093180}, 0x14001175a30, {0x0, 0x0})
	/Users/xxx/go/pkg/mod/github.com/twpayne/go-xmlstruct@v1.2.0/element.go:213 +0xa40
github.com/twpayne/go-xmlstruct.(*Generator).Generate(0x1400007e750)
	/Users/xxx/go/pkg/mod/github.com/twpayne/go-xmlstruct@v1.2.0/generator.go:269 +0x440
main.run()
	/Users/xxx/go/pkg/mod/github.com/twpayne/go-xmlstruct@v1.2.0/cmd/goxmlstruct/main.go:65 +0x358
main.main()
	/Users/xxx/go/pkg/mod/github.com/twpayne/go-xmlstruct@v1.2.0/cmd/goxmlstruct/main.go:78 +0x1c
```
with

```bash
#!/usr/bin/env bash

file_content=$(cat "./testfile.xml")
echo $file_content | goxmlstruct -output test.go
```

The XML file is roughly 10,6 Mb big. Is that too big?
There's little to no info attached how to debug this.

**Comment by twpayne** [comment]
For info, the panic is happening because the XML file contains element names that are entirely non-alphanumeric characters.

**Comment by twpayne** [comment]
I've pushed tag `v1.3.0` with the fix. The minor version bump is because the fix changes the output of go-xmlstruct in some cases.

**Comment by kelzenberg** [comment]
> Please compress the file and attach it here.

Unfortunately I can't because it contains sensitive data.

> I've pushed tag v1.3.0 with the fix. 

Appreciate it. What a quick fix!
